# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    # - task: Docker@2
    #   displayName: Build and push an image to container registry
    #   inputs:
    #     command: buildAndPush
    #     repository: starterjavascript
    #     tags: 1.0
    #     containerRegistry: csgdtc_registry_connection

    - task: Kubernetes@1
      displayName: kubectl create
      inputs:
         connectionType: Kubernetes Service Connection
         kubernetesServiceEndpoint: aks-remoteshutdown-connection
         command: create
         arguments: secret generic xyss -n dev-remoteshutdown
